### ISSUE TITLE
Have you considered adding long breaks?

### ISSUE THREAD

**Issue by escobar5** [stevenselcuk/Pomosh-macOS#1]
Hi, first of all let me thank you, I'm loving Pomosh. 

Have you considered adding long breaks to Pomosh? I really miss them.

**Comment by stevenselcuk** [comment]
> Hi, first of all let me thank you, I'm loving Pomosh.
> 
> Have you considered adding long breaks to Pomosh? I really miss them.

Hello👋🏻, thanks for your feedback
Of course, why not. I gonna extend break time duration range to 20 minutes on the next update

**Comment by escobar5** [comment]
Hi, sorry for the confusion, what I meant was that the pomodoro technique consists in a series of work time (25 min) + short break (5 min), and after 4 series then you take a **long break** (15 to 30 minutes), that's the long break I was talking about.

**Comment by stevenselcuk** [comment]
Ah, I got it. It's my bad. It's ok I will add this as an option.

**Comment by stevenselcuk** [comment]
Long break times have added to every 4th rounds break with v1.0.1
