### ISSUE TITLE
Poor display on specific full screen apps

### ISSUE THREAD

**Issue by Vlad412** [stevenselcuk/Pomosh-macOS#11]
**Describe the bug**

Hello, there is a little issue with display :

<img width="1440" alt="Screenshot 2021-07-04 at 22 58 38" src="https://user-images.githubusercontent.com/22870742/124399951-48cc3800-dd1f-11eb-89a0-7cf61bf6a6c4.png">

**To Reproduce**
1. Open chrome or similar app in fullscreen.
2. Click on pomosh in menubar.
3. Move your mouse down without closing pomosh.
4. See the display.

**Expected behavior**
It could be nice if the menubar did't hide when pomosh is open.

**Desktop (please complete the following information):**
 - OS: Macbook Air 13

Otherwise, thanks for the app it's very good !

**Comment by stevenselcuk** [comment]
needs some refactor. currently, it uses popover instead of a window with blur effect & relative positioning

**Comment by stevenselcuk** [comment]
Added to release 1.0.5 on AppStore
