### ISSUE TITLE
change color

### ISSUE THREAD

**Issue by bashery** [stevenselcuk/Pomosh-macOS#12]
Hello Steven. Thanks for this wonderful app. I have tried more than ten similar apps. This app was the best.
I have a small note. The time in yellow/green looks very bad on the gray background. It is suitable for dark background. But it is very bad with the gray background. It is good to change the color when the background is gray or the system is in light mode.
That's it. thank you very much. 
<img width="472" alt="Screen Shot 2021-09-23 at 16 40 00" src="https://user-images.githubusercontent.com/48377058/134521223-a4b5a85e-4e46-4e52-b668-aafc171ac9d1.png">

**Comment by stevenselcuk** [comment]
Added to release 1.0.5 on AppStore

**Comment by bashery** [comment]
I love it. Thanks Steven.
