### ISSUE TITLE
Pomosh Ignores "cycles" Setting

### ISSUE THREAD

**Issue by whateverforever** [stevenselcuk/Pomosh-macOS#5]
**Describe the bug**
When I change the number of cycles in the settings, it immediately forgets it. New timers always assume 5 cycles.

**To Reproduce**
1. Open Pomosh
2. Click on Settings
3. Change cycles to two flames
4. Start timer, note that it displays 5

**Expected behavior**
I expect the main screen to show only two flames

**Screenshots**

**Desktop (please complete the following information):**
 - macOS Big Sur 11.0.1

**Additional context**
Other settings such as duration work as expected

**Comment by stevenselcuk** [comment]
I reproduced the issue and fixed it with commit b218a31
