### ISSUE TITLE
reduce cpu usage

### ISSUE THREAD

**Issue by anisg** [stevenselcuk/Pomosh-macOS#7]
Not sure this is a bug, but when running a Pomodoro with Pomosh, the CPU jump to 10% - 15% usage constant.
<img width="400" alt="Screenshot 2021-02-16 at 14 18 56" src="https://user-images.githubusercontent.com/17178399/108068202-1072d880-7062-11eb-8084-51899760714c.png">

While when it's not running it just displays 0% CPU which is normal
<img width="400" alt="Screenshot 2021-02-16 at 14 19 23" src="https://user-images.githubusercontent.com/17178399/108068225-1799e680-7062-11eb-8a59-794ed166e71e.png">

Love Pomosh for its simplicity, so just wondering if this 15% cpu usage is normal or if it's possible to do some optimization (e.g: no loop, only do a callback every 1 second etc...) I'm not a swift developer so can't help at this point.

Anyway, keep up the good work, and thanks!

**Comment by IvanWei** [comment]
CPU usage 94.6% which runs the more sessions until long break time.
macOS version: 11.5.1 (macbook pro 15-inch, Mid 2015)

![image](https://user-images.githubusercontent.com/84758153/129861830-6d546233-f9ff-4484-9c72-91088f335e40.png)

**Comment by bashery** [comment]
Hello friend. 
 I just unanimated the progress ring and got a decent result.
Performance improved from 15% to 2%. 
 The user will not feel any lack of animation.

**Comment by baxiry** [comment]
Hi !
I made a small modification, the processor consumption improved from  15% to 2%.

<img width="469" alt="Screen Shot 2021-09-28 at 23 12 04" src="https://user-images.githubusercontent.com/48377058/135158912-51cb48d7-f6c1-4af2-b409-0076d31b9f98.png">

**Comment by bashery** [comment]
I know it's not a perfect solution, but it's a good temporary solution.
Nobody will notice the importance of the lack of animation.
I just commented out this line of code.
<img width="398" alt="Screen Shot 2021-09-28 at 23 34 23" src="https://user-images.githubusercontent.com/48377058/135161568-949e44f4-d378-462d-858a-7f2d92f00a09.png">

**Comment by stevenselcuk** [comment]
@bashery 's PR solves this issue (reduce from %18 to % 2 on MBP Apple Silicon) So it's closed. Thanks again @bashery.   

--
