### ISSUE TITLE
Dont show timer in bar icon

### ISSUE THREAD

**Issue by egorgam** [stevenselcuk/Pomosh-macOS#9]
It would be useful to be able to turn off the timer on the application icon in the tray, because sometimes it is stressful, like the countdown in timed missions in video games.

**Comment by stevenselcuk** [comment]
I'll add a toggle to change the countdown to just a 🍅.  Wait for the next release. 👍

**Comment by egorgam** [comment]
So how soon a new version may be released?🌚

**Comment by stevenselcuk** [comment]
🤔 As soon as possible. It has been a long time.  Let's say next weekend.
